swagger: "2.0"
info:
  version: "0.0.1"
  title: Integrety Referential
# during dev, should point to your local machine
host: localhost:10080
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /enrollAStudent:
    x-swagger-router-controller: controller
    post:
      description: Enroll a student in a course
      operationId: enrollStudentInCourse
      tags:
        - Enroll
      parameters:
        - name: uni
          in: query
          description: The uni of the student 
          required: true
          type: string
        - name: callno
          in: query
          description: The callno of the course
          required: true
          type: number
      responses:
        "200":
          description: Enroll Successfully
          schema:
            $ref: '#/definitions/EnrollResponse'
        "401":
          description: No Such A Course
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /removeAStudent:
    x-swagger-router-controller: controller
    post:
      description: Remove a student from a course
      operationId: removeStudentFromCourse
      tags:
        - Enroll
      parameters:
        - name: uni
          in: query
          description: The uni of the student 
          required: true
          type: string
        - name: callno
          in: query
          description: The callno of the course
          required: true
          type: number
      responses:
        "200":
          description: Remove Successfully
          schema:
            $ref: '#/definitions/EnrollResponse'
        "401":
          description: No Such A Course
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw

# complex objects have schema definitions
definitions:
  EnrollResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
